version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: germantrust_datawarehouse
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: germantrust2025
      MYSQL_DATABASE: germantrust_dw
      MYSQL_USER: dwuser
      MYSQL_PASSWORD: dwpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql-scripts:/docker-entrypoint-initdb.d/
      - ./data:/var/lib/mysql-files/
    command: --secure-file-priv=/var/lib/mysql-files/
    
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: germantrust_phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: dwuser
      PMA_PASSWORD: dwpassword
    depends_on:
      - mysql

volumes:
  mysql_data:
